[18.12.2024  8:36:49,45] Running enslige_mindreårige.py 
Loaded .env file from: D:\Scripts\analyse\Telemark\Python\token.env
X_FUNCTIONS_KEY loaded successfully.
Loaded .env file from: D:\Scripts\analyse\Telemark\Python\token.env
GITHUB_TOKEN loaded successfully.
Fylker CSV data loaded successfully.
Kommuner CSV data loaded successfully.
[18.12.2024 08:36:52,150 Deleted file from temp folder: bosetting_enslige_mindre�rige.csv

Traceback (most recent call last):
  File "D:\Scripts\analyse\Telemark\Python\Queries\09_Innvandrere_og_inkludering\Bosetting_av_flyktninger\enslige_mindre�rige.py", line 220, in <module>
    is_new_data = compare_to_github(df_telemark, file_name, github_folder, temp_folder)
  File "D:\Scripts\analyse\Telemark\Python\Helper_scripts\github_functions.py", line 174, in compare_to_github
    existing_data = pd.read_csv(pd.StringIO(existing_file_content), encoding='utf-8')
AttributeError: module 'pandas' has no attribute 'StringIO'
[18.12.2024  8:36:52,25] Script failed with error code 1 
