[18.12.2024  8:36:54,95] Running andel_sysselsatte_innvandrere.py 
Loaded .env file from: D:\Scripts\analyse\Telemark\Python\token.env
X_FUNCTIONS_KEY loaded successfully.
Loaded .env file from: D:\Scripts\analyse\Telemark\Python\token.env
GITHUB_TOKEN loaded successfully.
VTFK Query JSON data loaded successfully.
TFK Query JSON data loaded successfully.
Her hentes tallene for Vestfold og Telemark i ['2023']
Her hentes tallene for Telemark i ['2023']
[18.12.2024 08:36:59,800 Deleted file from temp folder: andel_sysselsatte_innvandrere.csv

Traceback (most recent call last):
  File "D:\Scripts\analyse\Telemark\Python\Queries\09_Innvandrere_og_inkludering\Arbeid_og_inntekt\andel_sysselsatte_innvandrere.py", line 194, in <module>
    is_new_data = compare_to_github(df_filtered, file_name, github_folder, temp_folder)
  File "D:\Scripts\analyse\Telemark\Python\Helper_scripts\github_functions.py", line 174, in compare_to_github
    existing_data = pd.read_csv(pd.StringIO(existing_file_content), encoding='utf-8')
AttributeError: module 'pandas' has no attribute 'StringIO'
[18.12.2024  8:36:59,91] Script failed with error code 1 
