[18.12.2024  8:36:43,19] Running andel_flyktninger_og_arbeidsinnvandrere.py 
D:\Scripts\analyse\Telemark\Python\Queries\09_Innvandrere_og_inkludering\Innvandrerbefolkningen\andel_flyktninger_og_arbeidsinnvandrere.py:153: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pivot_arbeidsinnvandrere["Label"] = df_pivot_arbeidsinnvandrere["Kommune"]
D:\Scripts\analyse\Telemark\Python\Queries\09_Innvandrere_og_inkludering\Innvandrerbefolkningen\andel_flyktninger_og_arbeidsinnvandrere.py:154: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_pivot_flyktninger["Label"] = df_pivot_flyktninger["Kommune"]
D:\Scripts\analyse\Telemark\Python\Helper_scripts\github_functions.py:153: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  input_df[col] = input_df[col].astype(str).str.encode('utf-8').str.decode('utf-8')
D:\Scripts\analyse\Telemark\Python\Helper_scripts\github_functions.py:153: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  input_df[col] = input_df[col].astype(str).str.encode('utf-8').str.decode('utf-8')
Loaded .env file from: D:\Scripts\analyse\Telemark\Python\token.env
X_FUNCTIONS_KEY loaded successfully.
Loaded .env file from: D:\Scripts\analyse\Telemark\Python\token.env
GITHUB_TOKEN loaded successfully.
Flyktninger og arbeidsinnvandrere CSV data loaded successfully.
Selected data from year 2024-01-01 00:00:00
[18.12.2024 08:36:46,435 Deleted file from temp folder: andel_arbeidsinnvandrere.csv

Traceback (most recent call last):
  File "D:\Scripts\analyse\Telemark\Python\Queries\09_Innvandrere_og_inkludering\Innvandrerbefolkningen\andel_flyktninger_og_arbeidsinnvandrere.py", line 182, in <module>
    is_new_data1 = compare_to_github(
  File "D:\Scripts\analyse\Telemark\Python\Helper_scripts\github_functions.py", line 174, in compare_to_github
    existing_data = pd.read_csv(pd.StringIO(existing_file_content), encoding='utf-8')
AttributeError: module 'pandas' has no attribute 'StringIO'
[18.12.2024  8:36:46,55] Script failed with error code 1 
