[13.12.2024 12:35:58,56] Running enslige_mindreÃ¥rige.py 
Loaded .env file from: D:\Scripts\analyse\Telemark\Python\token.env
X_FUNCTIONS_KEY loaded successfully.
Loaded .env file from: D:\Scripts\analyse\Telemark\Python\token.env
GITHUB_TOKEN loaded successfully.
Request error in Fylker: 500 Server Error: Internal Server Error for url: https://app-simapi-prod.azurewebsites.net/download_csv/f/nslige_mindrearige
Error occurred: 500 Server Error: Internal Server Error for url: https://app-simapi-prod.azurewebsites.net/download_csv/f/nslige_mindrearige
Error notification email sent successfully.
Traceback (most recent call last):
  File "D:\Scripts\analyse\Telemark\Python\Queries\09_Innvandrere_og_inkludering\Bosetting_av_flyktninger\enslige_mindreårige.py", line 38, in <module>
    df_fylker = fetch_data(
  File "D:\Scripts\analyse\Telemark\Python\Helper_scripts\utility_functions.py", line 46, in fetch_data
    response.raise_for_status()
  File "C:\Users\_eve1509\AppData\Local\anaconda3\envs\analyse\lib\site-packages\requests\models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://app-simapi-prod.azurewebsites.net/download_csv/f/nslige_mindrearige

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Scripts\analyse\Telemark\Python\Queries\09_Innvandrere_og_inkludering\Bosetting_av_flyktninger\enslige_mindreårige.py", line 50, in <module>
    raise RuntimeError(
RuntimeError: A critical error occurred during data fetching, stopping execution.
[13.12.2024 12:36:01,70] Script failed with error code 1 
