Loaded .env file from: C:\Users\eve1509\OneDrive - Telemark fylkeskommune\Github\Telemark\Python\token.env

X_FUNCTIONS_KEY loaded successfully.

Loaded .env file from: C:\Users\eve1509\OneDrive - Telemark fylkeskommune\Github\Telemark\Python\token.env

GITHUB_TOKEN loaded successfully.

Email notifications disabled. Errors in strompriser.py were not sent.

Email notifications disabled. Errors in strompriser.py were not sent.

Error occurred: A critical error occurred while processing the data, stopping execution.

Email notifications disabled. Errors in strompriser.py were not sent.



Errors:
Traceback (most recent call last):

  File "C:\Users\eve1509\OneDrive - Telemark fylkeskommune\Github\Telemark\Python\Queries/04_Klima_og_energi/Kraft og energi/Strompriser/strompriser.py", line 73, in fetch_energy_prices

    raise ValueError("No price data found in the API response")

ValueError: No price data found in the API response



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "C:\Users\eve1509\OneDrive - Telemark fylkeskommune\Github\Telemark\Python\Queries/04_Klima_og_energi/Kraft og energi/Strompriser/strompriser.py", line 187, in <module>

    df_prices = fetch_energy_prices(

  File "C:\Users\eve1509\OneDrive - Telemark fylkeskommune\Github\Telemark\Python\Queries/04_Klima_og_energi/Kraft og energi/Strompriser/strompriser.py", line 88, in fetch_energy_prices

    raise RuntimeError(

RuntimeError: A critical error occurred while processing the data, stopping execution.



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "C:\Users\eve1509\OneDrive - Telemark fylkeskommune\Github\Telemark\Python\Queries/04_Klima_og_energi/Kraft og energi/Strompriser/strompriser.py", line 252, in <module>

    raise RuntimeError(

RuntimeError: A critical error occurred during execution, stopping script.


ERROR conda.cli.main_run:execute(124): `conda run python C:\Users\eve1509\OneDrive - Telemark fylkeskommune\Github\Telemark\Python\Queries/04_Klima_og_energi/Kraft og energi/Strompriser/strompriser.py` failed. (See above for error)
